language: node_js
node_js:
    - node

script: yarn run $RUN_SCRIPT
deploy:
    provider: script
    skip_cleanup: true
    script: bash build/deploy.sh
    on:
        all_branches: true
        condition: $TRAVIS_BRANCH =~ ^(master|dev)$
