name: Build Project

on: 
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Use modern yarn
        run: |
          corepack enable
          yarn set version stable

      - name: Version output
        run: "node: $(node -v) – yarn: $(yarn -v) – git: $(git --version)"

      - name: update browserslist
        run: npx -y browserslist@latest --update-db
      
      - name: yarn install
        run: yarn install --immutable
      
      - run: |
        echo "TYPE=$(If[[${{ github.ref == 'refs/heads/master' }}]];then 'stable'; else 'dev';)" >> $GITHUB_ENV
        yarn run $TYPE