name: Dev Workflow

on:
    push:

jobs:
    build:
        if: ${{ !contains(github.event.head_commit.message, 'skip ci') || !contains(github.event.head_commit.message, 'ci-push') }}
        uses: ./.github/workflows/build.yml
        secrets: inherit

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: list content of dist
              if: ${{ github.ref == 'refs/heads/dev' }}
              run: ls -la dist

            - name: Install SSH Key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_DEPLOY_KEY }}
                  known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

            - name: Add known_hosts
              run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Deployment
              if: ${{ success() }}
              run: |
                  sudo apt-get install -y rsync

                  rsync -run --exclude dist/static/* dist/ "/${{ needs.build.outputs.type }}" 
                  exit 0

    git_push:
        needs: [build, deploy]
        runs-on: ubuntu-latest
        steps:
            - name: Push to Git
              if: ${{ success() }}
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_user_name: ${{ secrets.GIT_USERNAME }}
                  commit_user_email: ${{ secrets.GIT_EMAIL }}
                  commit_author: Build Server <developer@lss-manager.de>
                  commit_message: '📦 Version ${{ needs.build.outputs.version }} [skip ci]'
